#!/bin/bash

# ------------------------------------------------------------------------------
# Run some health checks. Can be run standalone or as git pre-commit.
# ------------------------------------------------------------------------------

PYTHON_CHECKS="yes"
YAML_CHECKS="yes"

# ------------------------------------------------------------------------------
function info {
	echo "[34;1m$*[0m" >& 2
}

function warning {
	echo "[35;1mWARNING: $*[0m" >& 2
}

function error {
	echo "[31;1mERROR: $*[0m" >& 2
}

function abort {
	error $*
	exit 1
}

# Get the git branch being committed.
function git_branch {
	git rev-parse --abbrev-ref HEAD
}

# Output to stderr
exec 1>&2

# ------------------------------------------------------------------------------
# In case we need to distinguish between manual and git hook mode
case "$1"
in
	-m | --manual)	mode=manual;;
	*)		mode=hook;;
esac

# ------------------------------------------------------------------------------
# Branch checks
branch=$(git_branch)

case "$branch"
in
	master | main)

		if [ "$mode" == hook ]
		then
			warning "‼️  You should not be committing to ${branch}!"
		else
			info "Don't forget - Check on $branch branch ✅. Commit ❌"
		fi
		;;
	*)
		;;
esac

# ------------------------------------------------------------------------------
# Python.

if [ "$PYTHON_CHECKS" == "yes" ]
then
	# Look for Python files not ending in .py
	HIDDEN_PYTHON=$(
		find . -type f -perm -u=x ! -name '*.py' ! -name '*.sh' ! -path './venv/*' \
			! -path './.??*/*' ! -path './doc/*' ! -path './untracked/*' \
			! -path './dist/*' ! -path './*egg-info*' \
			! -path './test/*' \
			-print0 | xargs -r -0 file | grep 'Python script' | cut -d: -f1
	)

	info "Checking Python code ..."

	# Ruff is heaps faster than flake8 so we run that first
	info "... ruff ..."
	ruff check . || abort Ruff checks failed
	if [ "$HIDDEN_PYTHON" != "" ]
	then
		ruff check $HIDDEN_PYTHON || abort Ruff checks failed
	fi

	info "... flake8 ..."
	flake8 . || abort Flake8 checks failed
	if [ "$HIDDEN_PYTHON" != "" ]
	then
		flake8 $HIDDEN_PYTHON || abort Flake checks failed
	fi
fi

# ------------------------------------------------------------------------------
# YAML hygiene.

if [ "$YAML_CHECKS" == "yes" ]
then
	info "Checking YAML hygiene ..."
	yamllint . || abort YAML checks failed
fi
